### ISSUE TITLE
Retrieve metrics on different Try coding events

### ISSUE THREAD

**Issue by jmejia** [turingschool/try-turing#11]
What are conversion rates for:
* FE or BE only vs combined
* Evenings vs weekend

* Do we use the same curriculum for these events?
* What are our current target audiences?
* What is the demographic data for each type of event?
* Can we tailor the content to attendees?
* When it's in Denver should we always host? Parking?

**Comment by srt32** [comment]
@jmejia could you elaborate on what we'd be looking for here?
